# log:
#   level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: ":443"
    http3: {}
    http:
      tls:
        certResolver: customResolver

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /services
    watch: true

api:
  dashboard: false

ping:
  manualRouting: true

tls:
  options:
    default:
      certificate:
        generate:
          domains:
            - '*.{{ env "NETWORK_DOMAIN" }}'

# certificatesResolvers:
#   customResolver:
#     acme:
#       storage: /acme/acme.json
#       httpChallenge:
#         entryPoint: web