http:
  routers:
    ping:
      entryPoints:
      - web
      - web-secure
      service: ping@internal
      rule: Host(`{{ env "NETWORK_DOMAIN" }}`) && Path(`/ping`)
      middlewares:
      - ping-middleware
      - cors-middleware

  middlewares:
    ping-middleware:
      headers:
        customResponseHeaders:
          Cache-Control: "no-store, no-cache, must-revalidate, proxy-revalidate"
          Pragma: "no-cache"
          Expires: "0"
          Surrogate-Control: "no-store"
          X-Ping: "pong"

    cors-middleware:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - HEAD
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true
