ping:
  manualRouting: true

http:
  routers:
    ping:
      entryPoints:
      - web
      - web-secure
      service: ping@internal
      rule: Host(`{{ env "NETWORK_DOMAIN" }}`)
      middlewares:
      - ping-middleware
      - cors-middleware

  middlewares:
    ping-middleware:
      headers:
        customResponseHeaders:
          X-Ping: "pong"

    cors-middleware:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - HEAD
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true
