http:
  routers:
    sentry:
      entryPoints:
      - web
      - web-secure
      service: sentry-service
      rule: Host(`{{ env "NETWORK_DOMAIN" }}`) && Path(`/sentry.js`)

  services:
    sentry-service:
      loadBalancer:
        servers:
        - url: {{ env "SENTRY_JS_URL" }}